<div class="card card-warning">
    <div class="card-header">
        <h3 class="card-title">Payment</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <form role="form">
            <!-- text input -->
            <div class="form-group">
                <label>Tên</label>
                <input type="text" class="form-control" placeholder="Enter ...">
            </div>
            <div class="form-group">
                <label>Tài khoản</label>
                <input type="text" class="form-control" placeholder="Enter ...">
            </div>
            <div class="form-group">
                <label>Tài khoản chuyển tiền</label>
                <input type="text" class="form-control" placeholder="Enter ...">
            </div>

            <!-- textarea -->
            <div class="form-group">
                <label>Nội dung</label>
                <textarea class="form-control" rows="3" placeholder="Enter ..."></textarea>
            </div>
            <button type="button" style="width: 10%;font-size: 15px" class="btn btn-block btn-info btn-lg">Thực hiện</button>
        </form>
    </div>