<div class="card card-warning">
    <div class="card-header">
        <h3 class="card-title">Nạp tiền</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <form role="form">
            <!-- text input -->
            <div class="form-group">
                <label>Số tiền </label>
                <input type="text" class="form-control" placeholder="Enter ...">
            </div>
            <div class="form-group">
                <label>Ngân hàng liên kết</label>
                <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                </select>
            </div>

            <button type="button" style="width: 10%;font-size: 15px" class="btn btn-block btn-info btn-lg">Thực hiện</button>
        </form>
    </div>